# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-20 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0003_auto_20180215_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='canvas_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('full_street', models.CharField(max_length=100)),
                ('orig_address', models.CharField(max_length=100)),
                ('voters', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('NUMBER', models.IntegerField()),
                ('STREET', models.CharField(max_length=100)),
                ('LAT', models.FloatField()),
                ('LON', models.FloatField()),
            ],
        ),
    ]
