# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-20 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0004_canvas_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='bad_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('full_street', models.CharField(max_length=100)),
                ('voters', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('orig_address', models.CharField(max_length=100)),
            ],
        ),
    ]
