# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-22 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0007_bad_geo_data_failsafe'),
    ]

    operations = [
        migrations.CreateModel(
            name='intersections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street1', models.CharField(max_length=100)),
                ('street2', models.CharField(max_length=100)),
                ('distance', models.FloatField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('region', models.CharField(max_length=100)),
            ],
        ),
    ]
