# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-23 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutter', '0008_intersections'),
    ]

    operations = [
        migrations.CreateModel(
            name='region_progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('voter_json_complete', models.BooleanField(default=False)),
                ('bad_data_complete', models.BooleanField(default=False)),
                ('canvas_data_complete', models.BooleanField(default=False)),
                ('bad_geo_failsafe_data', models.BooleanField(default=False)),
                ('last_street', models.CharField(max_length=100)),
            ],
        ),
    ]
